# Generated by Django 3.0.4 on 2020-03-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('tamanho', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Tamanho da Rota em Km')),
            ],
        ),
    ]
