# Generated by Django 3.0.4 on 2020-04-06 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0004_auto_20200327_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotas',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotas',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
